### ISSUE TITLE
Support initWithCoder:

### ISSUE THREAD

**Issue by silvansky** [skysh3n/CSChartsView#2]
Now only code-based initialization supported. I wish I could just put a custom view in IB to make it work.

**Comment by skysh3n** [comment]
OK,I will take your advice into consideration,but I'm really busy these days.I'll try when I have more time.

**Comment by silvansky** [comment]
I can fix it and make a pull request - hope you'll accept it.

**Comment by skysh3n** [comment]
Oh,really~~,that's great!! You can pull your request and I'll check it and merge it in

**Comment by silvansky** [comment]
https://github.com/sk344208651/CSChartsView/pull/3
Here it is.

**Comment by silvansky** [comment]
And you should just update your podspec and push a new pod version...

**Comment by skysh3n** [comment]
OK ,thank you ,I'll update the pod this weekend

**Comment by silvansky** [comment]
Will you accept pull request?
